name: pre-commit

on:
    workflow_call:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-mise
              uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2

            - name: setup-rust-toolchain
              uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # stable
              with:
                  toolchain: nightly
                  components: rustfmt, clippy

            - name: cache-deps
              env:
                  CACHE_KEY_PREFIX: deps-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}
                  CACHE_KEY_DEPS: ${{ hashFiles('uv.lock', '.pre-commit-config.yaml') }}
              uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
              with:
                  path: |
                      ~/.cache/pre-commit
                      ~/.cache/ruff
                      ~/.bun/install/cache
                      ~/.local/share/uv
                      ~/.cache/uv
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/.venv
                  key: ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-${{ github.run_id }}-${{ github.run_attempt }}
                  restore-keys: |
                      ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-${{ github.run_id }}-
                      ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-
                      ${{ env.CACHE_KEY_PREFIX }}-

            - name: setup-path
              run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

            - name: run-pre-commit
              run: uv run pre-commit run --all-files
